import { escapeHtml as e } from '../../src/site.js';
import { mounted } from '../../src/model.js';
import { artifactModel, collectionModel, inlineJson, localUrl } from './model.js';

export function artifactPath(collection, artifact) { return collection.path + artifact.id + '/'; }
const asset = (site, src) => mounted(site, localUrl(src));
const initials = name => name.split(/\s+/).slice(0, 2).map(word => word[0]).join('');
function byline(site, person) {
  if (!person) return '';
  return `<div class="artifact-byline">${person.photo ? `<img src="${e(asset(site, person.photo.src))}" alt="${e(person.photo.alt)}" width="56" height="56" loading="lazy">` : `<span class="artifact-initials" aria-hidden="true">${e(initials(person.name))}</span>`}<span><strong>${person.profile_url ? `<a href="${e(person.profile_url)}" rel="noopener noreferrer">${e(person.name)}</a>` : e(person.name)}</strong>${person.role ? `<span>${e(person.role)}</span>` : ''}</span></div>`;
}
function resources(site, artifact) {
  return artifact.resources.map(resource => {
    const label = resource.label || (resource.type === 'oci' ? 'OCI artifact reference' : resource.type === 'mouseion' ? 'Mouseion reference' : 'Open artifact');
    const url = resource.type === 'local' ? asset(site, resource.url) : resource.url;
    return `<li>${url ? `<a href="${e(url)}"${resource.type !== 'local' ? ' rel="noopener noreferrer"' : ''}>${e(label)} ↗</a>` : `<strong>${e(label)}</strong>`}${resource.identifier ? `<code>${e(resource.identifier)}</code>` : ''}${resource.digest ? `<code>${e(resource.digest)}</code>` : ''}<span class="artifact-resource-meta">${e([resource.type, resource.media_type, resource.bytes !== undefined ? `${resource.bytes.toLocaleString('en')} bytes` : ''].filter(Boolean).join(' · '))}</span></li>`;
  }).join('');
}
export function renderArtifactCard(site, collectionInput, input) {
  const collection = collectionModel(collectionInput), artifact = artifactModel(input);
  const href = mounted(site, artifactPath(collection, artifact));
  return `<article class="artifact-card artifact-${e(artifact.presentation)}" data-artifact-id="${e(artifact.id)}">${artifact.image ? `<a class="artifact-cover" href="${e(href)}"><img src="${e(asset(site, artifact.image.src))}" alt="${e(artifact.image.alt)}" loading="lazy" width="640" height="400"></a>` : `<div class="artifact-motif" aria-hidden="true"><span>❦</span></div>`}<div class="artifact-card-copy"><p class="artifact-kicker">${e(artifact.kind)} · <time datetime="${e(artifact.created_at)}">${e(artifact.created_at.slice(0, 10))}</time></p><h2><a href="${e(href)}">${e(artifact.title)}</a></h2>${artifact.quote ? `<blockquote><p>“${e(artifact.quote)}”</p></blockquote>` : ''}<p>${e(artifact.ingress)}</p>${byline(site, artifact.person)}<a class="artifact-open" href="${e(href)}">Explore this ${e(artifact.kind)} →</a></div></article>`;
}
function document(site, collection, title, description, canonical, body, data, image, { privatePage = false, scripts = [] } = {}) {
  // SVG remains useful for illustrations, but social/email consumers need a
  // raster cover. Do not advertise an unsupported SVG as the OG image.
  if (image?.src.endsWith('.svg')) image = site.socialImage ? { src: site.socialImage, alt: title } : null;
  return `<!doctype html><html lang="${e(site.defaultLocale)}" data-artifact-theme="${e(collection.theme)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)} · ${e(site.name)}</title><meta name="description" content="${e(description)}">${privatePage ? '<meta name="robots" content="noindex,nofollow">' : `<link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="website"><meta property="og:url" content="${e(canonical)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}">${image ? `<meta property="og:image" content="${e(site.origin + asset(site, image.src))}"><meta property="og:image:alt" content="${e(image.alt)}"><meta name="twitter:card" content="summary_large_image">` : '<meta name="twitter:card" content="summary">'}`}${['tokens.css', 'site-tokens.css', 'artifact-tokens.css', 'artifacts.css'].map(file => `<link rel="stylesheet" href="${e(mounted(site, '/assets/' + file))}">`).join('')}${scripts.map(file => `<script src="${e(mounted(site, '/assets/' + file))}" defer></script>`).join('')}</head><body><a class="artifact-skip" href="#main">Skip to content</a><div class="artifact-book"><div class="artifact-ribbon" aria-hidden="true"></div><header class="artifact-header"><a href="${e(mounted(site, collection.path))}">${e(site.name)}</a><span>A collection of thoughtful things</span></header><main id="main">${body}</main><footer class="artifact-footer"><span>Made with care · Offered with gratitude</span><a href="https://ragbaz.cc">From the RAGBAZ workshop ↗</a></footer><div class="artifact-ribbon" aria-hidden="true"></div></div>${data ? `<script type="application/json" id="artifact-data">${inlineJson(data)}</script>` : ''}</body></html>`;
}
export function renderCollection(site, input, items) {
  const collection = collectionModel(input), artifacts = items.map(artifactModel);
  if (collection.mode === 'singleton' && artifacts.length === 1) return renderArtifact(site, collection, artifacts[0], { singleton: true });
  const body = `<section class="artifact-hero"><p class="artifact-kicker">${e(collection.mode)} / ${e(collection.id)}</p><h1>${e(collection.title)}</h1><p class="artifact-deck">${e(collection.ingress)}</p><div class="artifact-welcome"><span aria-hidden="true">❦</span><p>Something beautiful to keep.<br>Something useful to carry forward.</p></div></section><section class="artifact-gallery" aria-labelledby="gallery-title"><div class="artifact-section-head"><h2 id="gallery-title">The gifts, one by one.</h2><p>${artifacts.length} ${artifacts.length === 1 ? 'artifact' : 'artifacts'}</p></div>${artifacts.length ? `<div class="artifact-grid">${artifacts.map(item => renderArtifactCard(site, collection, item)).join('')}</div>` : '<p class="artifact-empty">This collection is waiting for its first shared artifact.</p>'}</section>`;
  return document(site, collection, collection.title, collection.ingress, site.origin + mounted(site, collection.path), body, { schema: 'ragbaz.artifact-collection/v1', collection, artifacts }, artifacts[0]?.social_image || artifacts[0]?.image);
}
export function renderArtifact(site, input, item, { singleton = false } = {}) {
  const collection = collectionModel(input), artifact = artifactModel(item);
  const body = `<section class="artifact-hero"><p class="artifact-kicker">${e(artifact.kind)} / ${e(collection.title)}</p><h1>${e(artifact.title)}</h1><p class="artifact-deck">${e(artifact.ingress)}</p>${artifact.image ? `<img class="artifact-hero-image" src="${e(asset(site, artifact.image.src))}" alt="${e(artifact.image.alt)}" width="1200" height="630">` : ''}${artifact.quote ? `<blockquote class="artifact-feature-quote"><p>“${e(artifact.quote)}”</p></blockquote>` : ''}${byline(site, artifact.person)}</section>${(artifact.body || []).map((section, index) => `<section class="artifact-prose" id="section-${e(section.id)}"><p class="artifact-kicker">${String(index + 1).padStart(2, '0')} / A closer look</p><h2>${e(section.title)}</h2>${section.paragraphs.map(p => `<p>${e(p)}</p>`).join('')}</section>`).join('')}${artifact.resources.length ? `<section class="artifact-prose"><h2>Open, use, explore.</h2><ul class="artifact-resources">${resources(site, artifact)}</ul></section>` : ''}<p class="artifact-back"><a href="${e(mounted(site, collection.path))}">← All the gifts in this collection</a></p>`;
  return document(site, collection, artifact.title, artifact.ingress, site.origin + mounted(site, singleton ? collection.path : artifactPath(collection, artifact)), body, { schema: 'ragbaz.artifact-page/v1', artifact }, artifact.social_image || artifact.image);
}
export function renderInbox(site, collection) {
  const body = `<section class="artifact-hero"><p class="artifact-kicker">Private / Editorial inbox</p><h1>A place to receive.<br>A place to give.</h1><p class="artifact-deck">Quotes, useful artifacts, thoughtful replies. Record the permission, choose the right collection, then publish when you are ready.</p></section><section class="artifact-prose"><h2>Receive or prepare an artifact</h2><form id="artifact-compose" data-endpoint="${e(mounted(site, '/api/exchange'))}"><label>JSON submission envelope<textarea name="envelope" rows="12" required spellcheck="false" placeholder="Paste a ragbaz.artifact-submission/v1 envelope"></textarea></label><p>Both directions use the same envelope. Sender/recipient contact information stays in this private inbox.</p><button type="submit">Add to inbox</button></form><p role="status" aria-live="polite" id="artifact-status"></p></section><section class="artifact-gallery"><div class="artifact-section-head"><h2>Awaiting your attention</h2><button id="artifact-refresh" type="button">Refresh</button></div><div id="artifact-inbox"></div><button id="artifact-more" type="button" hidden>Load more</button></section>`;
  return document(site, collection, 'Artifact inbox', 'Private artifact review', '', body, null, null, { privatePage: true, scripts: ['artifact-inbox.js'] });
}
export function renderShare(site, collections) {
  const body = `<section class="artifact-hero"><p class="artifact-kicker">Share / Receive privately</p><h1>A thoughtful thing<br>to pass along.</h1><p class="artifact-deck">Send a quote, a link, a gift, or a useful piece of work. It enters a private inbox first; publication is a separate decision.</p></section><section class="artifact-prose"><form id="artifact-share" data-endpoint="${e(mounted(site, '/api/exchange/submit'))}"><label>Your name<input name="name" maxlength="160" autocomplete="name" required></label><label>Your email, kept private<input type="email" name="email" maxlength="254" autocomplete="email" required></label><label>Collection<select name="collection">${collections.map(c => `<option value="${e(c.id)}">${e(c.title)}</option>`).join('')}</select></label><label>Title<input name="title" maxlength="240" required></label><label>A short introduction<textarea name="ingress" rows="3" maxlength="1200" required></textarea></label><label>Your exact quote or opinion (optional)<textarea name="quote" rows="3" maxlength="3000"></textarea></label><label>Artifact link (optional, HTTPS)<input type="url" name="url" maxlength="2048"></label><label>Your profile or institutional page (optional, HTTPS)<input type="url" name="profile" maxlength="2048"></label><label>Photo source (optional; kept private for review)<input type="url" name="photo" maxlength="2048"></label><p>Names, profiles and photographs are not automatically verified or fetched. A photograph is only added to a public version after its use and source have been agreed.</p><fieldset><legend>What may be shared publicly, if selected?</legend>${['artifact', 'quote', 'name', 'profile'].map(scope => `<label><input type="checkbox" name="scope" value="${scope}"> ${e({ artifact: 'The artifact, title and introduction', quote: 'My exact quote', name: 'My chosen name', profile: 'My supplied profile link' }[scope])}</label>`).join('')}</fieldset><label><input type="checkbox" name="receive" required> You may keep this submission to review it and reply.</label><button type="submit">Send to the private inbox</button><p role="status" aria-live="polite" id="artifact-share-status"></p><div id="artifact-receipt" hidden><p>Save this receipt to request withdrawal. It is a private capability, not a public share link.</p><pre></pre><button type="button" id="artifact-revoke">Withdraw this submission</button></div><noscript><p>This structured submission form uses first-party JavaScript. You can instead send the text by email to <a href="mailto:ragbaz@proton.me">ragbaz@proton.me</a>.</p></noscript></form></section>`;
  return document(site, collections[0], 'Share a thoughtful artifact', 'Send an artifact to the private editorial inbox.', site.origin + mounted(site, '/share/'), body, null, null, { scripts: ['artifact-share.js'] });
}
export function renderEmail(site, input, item, { ready = true } = {}) {
  const collection = collectionModel(input), artifact = artifactModel(item);
  const href = site.origin + mounted(site, artifactPath(collection, artifact));
  const emailImage = artifact.social_image || artifact.image;
  const image = emailImage && !emailImage.src.endsWith('.svg') ? site.origin + asset(site, emailImage.src) : null;
  // Email clients do not inherit website CSS or scripts. Keep this table-based,
  // inline-styled and entirely derived from the same escaped public fields.
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(artifact.title)}</title></head><body style="margin:0;background:#e5d9c3;color:#283e33;font-family:Georgia,serif;"><div style="display:none;max-height:0;overflow:hidden;">${e(artifact.ingress)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px;"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#f3ead8;border:1px solid #b5ad94;"><tr><td style="padding:32px;border-top:6px solid #934831;"><p style="font:12px Arial,sans-serif;letter-spacing:2px;text-transform:uppercase;">${e(collection.title)} · ${ready ? 'A shared artifact' : 'Private draft preview'}</p><h1 style="font-size:38px;line-height:1.15;font-weight:normal;">${e(artifact.title)}</h1>${image ? `<img src="${e(image)}" alt="${e(emailImage.alt)}" width="536" style="width:100%;height:auto;display:block;">` : ''}${artifact.quote ? `<blockquote style="margin:24px 0;font-size:24px;line-height:1.45;">“${e(artifact.quote)}”</blockquote>` : ''}<p style="font-size:18px;line-height:1.7;">${e(artifact.ingress)}</p>${artifact.person ? `<p style="font-size:16px;">${e(artifact.person.name)}${artifact.person.role ? ' · ' + e(artifact.person.role) : ''}</p>` : ''}${ready ? `<p style="margin:28px 0;"><a href="${e(href)}" style="display:inline-block;padding:14px 22px;background:#283e33;color:#fbf6ea;text-decoration:none;font:16px Arial,sans-serif;">Open this ${e(artifact.kind)} →</a></p>` : '<p>This artifact has not been published. Its public link will become available after permission and editorial review.</p>'}<p style="font-size:15px;line-height:1.7;border-top:1px solid #b5ad94;padding-top:24px;">Made with care. Offered with gratitude.<br>No reply is required.</p></td></tr></table></td></tr></table></body></html>`;
  const plain = [collection.title, artifact.title, artifact.quote ? `“${artifact.quote}”` : '', artifact.ingress, artifact.person ? artifact.person.name + (artifact.person.role ? ' · ' + artifact.person.role : '') : '', ready ? href : 'Private draft: the public link is not yet available.', 'Made with care. Offered with gratitude. No reply is required.'].filter(Boolean).join('\n\n');
  return { subject: artifact.title, html, text: plain, schema: 'ragbaz.artifact-email/v1' };
}
