import { normalizeSite, homePage, mounted, pagePath, availableLocales, edition, publications } from './model.js';
import { FLEET, STUDIO, LOOM_ARTICLE } from './fleet.js';
export function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}
export function safeLink(value) {
  if (typeof value !== 'string') throw new Error('Link must be a string');
  const url = new URL(value);
  if (!['https:', 'mailto:'].includes(url.protocol) || url.username || url.password) throw new Error(`Unsupported link: ${value}`);
  return value;
}
export function validateSite(site) { return normalizeSite(site, safeLink); }
const THREAD = '<svg class="thread" viewBox="0 0 900 32" aria-hidden="true"><path d="M0 16H360q20-26 40 0t40 0t40 0t40 0t40 0H900" fill="none" stroke="currentColor" stroke-width="2"/></svg>';
const MARK = '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M8 9v30m8-30v30m8-30v30m8-30v30m8-30v30M5 16h38M5 24h38M5 32h38" fill="none" stroke="currentColor" stroke-width="3"/><path d="m8 39 32-30" fill="none" stroke="currentColor" stroke-width="4"/></svg>';

function contactForm(site, page, e) {
  return `<section class="interest-panel" id="interest"><div><p class="eyebrow">A conversation, not a sales funnel</p><h2>What would you like to build together?</h2><p>Ask a question, tell us what you need, offer a contribution or simply show your support. RAGBAZ is a software studio working toward kindness, mutual cooperation and the good of all beings.</p><p class="small">Prefer email? <a href="mailto:ragbaz@proton.me">ragbaz@proton.me</a></p></div>
<form data-contact action="${e(mounted(site, '/api/contact'))}" method="post" data-page="${e(page.path)}"><div class="form-grid"><label>Your name <span>(optional)</span><input name="name" autocomplete="name" maxlength="160"></label><label>Email <input name="email" type="email" autocomplete="email" maxlength="254" required></label></div><label>I’m interested in <select name="interest"><option value="question">Asking a question</option><option value="workflow">Using it in my workflow</option><option value="collaboration">Collaborating or contributing</option><option value="support">Supporting the work</option><option value="privacy">A privacy or data request</option></select></label><label>Tell us a little <textarea name="message" rows="4" maxlength="4000" required></textarea></label><label class="honeypot" aria-hidden="true">Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label><label class="check"><input name="consent" type="checkbox" required> RAGBAZ may keep this message, email, page and date to reply and connect my repeated requests across these projects.</label><label class="check"><input name="attribution_consent" type="checkbox"> I’m happy to share how I found this page (referrer and campaign tags, when available).</label><label class="check"><input name="link_account" type="checkbox"> If I later register with this email, RAGBAZ may connect this interest to my account.</label><p class="small">No advertising trackers or fingerprinting. Browser privacy signals take precedence over optional attribution. <a href="${e(mounted(site, '/privacy/'))}">How we look after your information</a>.</p><button class="button primary" type="submit">Start a conversation</button><p role="status" aria-live="polite" data-contact-status></p><noscript><p>You can submit this form without JavaScript, or use the email address above.</p></noscript></form></section>`;
}

export function renderPage(input, { missing = false, page, locale, listing = false, contact = false, sent = false } = {}) {
  const site = validateSite(input); page ??= homePage(site); locale ??= site.defaultLocale;
  const content = edition(site, page, locale), e = escapeHtml;
  const isHome = !missing && !listing && !contact && page.id === 'home';
  const title = missing ? `Page not found · ${site.name}` : listing ? `Publications · ${site.name}` : contact ? `Contact · ${site.name}` : `${content.title} · RAGBAZ`;
  const canonical = site.origin + (listing ? mounted(site, '/publications/') : contact ? mounted(site, '/contact/') : pagePath(site, page, content.locale));
  const active = FLEET.find(p => p.id === site.slug);
  const navigation = site.pages.filter(p => p.kind === 'page' && p.status !== 'draft' && p.id !== 'privacy').map(p => `<a href="${e(pagePath(site, p, locale))}">${e(p.title)}</a>`).join('');
  const fleetMenu = FLEET.filter(p => p.id !== site.slug).map(p => `<a href="${p.origin}"><strong>${p.name}</strong><span>${p.role}</span></a>`).join('');
  const listed = publications(site), shown = listed.slice(0, 5);
  const menuPubs = shown.map(p => `<a href="${e(pagePath(site, p, locale))}">${e(edition(site, p, locale).title)}</a>`).join('');
  const pubsIndex = `<a href="${e(mounted(site, '/publications/'))}">${listed.length > 5 ? `More in Publications (${listed.length}) →` : 'Publications'}</a>`;
  const header = `<header class="site-header"><a class="studio-brand" href="https://ragbaz.cc">${MARK}<span>RAGBAZ<small>A software studio for shared flourishing</small></span></a><details class="main-menu" data-main-menu><summary aria-label="Menu"><span class="menu-icon" aria-hidden="true">☰</span></summary><div class="menu-panel"><nav aria-label="This project"><a href="${e(mounted(site))}">${e(site.name)} home</a>${navigation}${menuPubs}${pubsIndex}<a href="${e(mounted(site, '/contact/'))}">Contact & support</a></nav><nav aria-label="Interoperable projects"><p class="menu-label">Work together</p>${fleetMenu}</nav><nav aria-label="Across the studio"><p class="menu-label">From RAGBAZ</p>${STUDIO.map(link => `<a href="${link.href}">${link.name}<span>${link.description}</span></a>`).join('')}</nav></div></details></header>`;
  const locales = availableLocales(site, page).map(l => `<a lang="${e(l.code)}" dir="${l.dir}" href="${e(pagePath(site, page, l.code))}"${l.code === content.locale ? ' aria-current="page"' : ''}>${e(l.label)}</a>`).join('');
  const reader = site.modules.reader ? `<details class="reader-controls"><summary>Reading preferences</summary><label>Theme <select data-reader="theme"><option value="paper">Paper</option><option value="sepia">Sepia</option><option value="white">White</option><option value="night">Night</option></select></label><label>Text <select data-reader="font"><option value="serif">Serif</option><option value="sans">Sans</option><option value="mono">Monospace</option></select></label><label>Print <select data-reader="paper"><option value="a4">A4</option><option value="a5">A5</option></select></label><button type="button" data-reader-print>Print</button><button type="button" data-reader-reset>Reset</button></details>` : '';
  const links = site.links.map((l, index) => `<a class="button${index === 0 ? ' primary' : ''}" href="${e(l.href)}">${e(l.label)}</a>`).join('');
  const sections = content.sections.map((s, index) => `<section class="prose-section" id="${e(s.id)}"><p class="eyebrow"><span class="section-number">${String(index + 1).padStart(2, '0')}</span> ${e(site.name)}</p><h2>${e(s.title)}</h2>${s.paragraphs.map(p => `<p>${e(p)}</p>`).join('')}${s.links?.length ? `<div class="text-links">${s.links.map(l => `<a href="${e(l.href)}">${e(l.label)} →</a>`).join('')}</div>` : ''}${s.code ? `<pre><code>${e(s.code)}</code></pre>` : ''}</section>`).join(THREAD);
  const defaultArticle = `<section class="featured-article" aria-labelledby="article-title"><div class="article-art" aria-hidden="true"><svg viewBox="0 0 320 210"><g fill="none" stroke="currentColor" stroke-width="3"><path d="M30 35v130m22-130v130m22-130v130m22-130v130m22-130v130M20 60h110M20 90h110M20 120h110M20 150h110"/><path d="M130 100c40-65 65 75 105 0"/><path d="M226 160v-75m30 75V60m30 100v-75"/></g><g class="grove-leaves"><ellipse cx="226" cy="70" rx="19" ry="32"/><ellipse cx="256" cy="50" rx="23" ry="40"/><ellipse cx="286" cy="70" rx="19" ry="32"/></g></svg><span>The loom · the grove · the connecting thread</span></div><div><p class="eyebrow">Begin with the human story</p><h2 id="article-title">${LOOM_ARTICLE.title}</h2><p>${LOOM_ARTICLE.description}</p><a class="button primary" href="${LOOM_ARTICLE.editions[0].href}">Read the illustrated field guide</a><nav class="article-languages" aria-label="Article languages">${LOOM_ARTICLE.editions.map(l => `<a href="${l.href}" lang="${l.code}" title="${e(l.title)}">${l.label}</a>`).join('')}</nav></div></section>`;
  const feature = site.featuredPublication;
  const featurePage = feature ? site.pages.find(p => p.id === feature.id) : null;
  const featureEdition = featurePage ? edition(site, featurePage, locale) : null;
  const article = feature ? `<section class="featured-article local-feature" aria-labelledby="article-title">${feature.image ? `<div class="article-art"><img src="${e(mounted(site, feature.image))}" alt="${e(feature.imageAlt)}" width="720" height="480" loading="lazy"></div>` : ''}<div><p class="eyebrow">${e(feature.label)}</p><h2 id="article-title">${e(featureEdition.title)}</h2><p>${e(featureEdition.description)}</p><a class="button primary" href="${e(pagePath(site, featurePage, featureEdition.locale))}">${e(feature.linkLabel)}</a></div></section>` : defaultArticle;
  const highlights = site.highlights?.length ? `<section class="highlights" aria-label="What this makes possible">${site.highlights.map(card => `<article><p class="eyebrow">${e(card.label)}</p><h3>${e(card.title)}</h3><p>${e(card.text)}</p></article>`).join('')}</section>` : '';
  const demo = site.demonstration;
  const demonstration = site.modules.demonstration ? `<section class="demonstration" id="demonstration" lang="${e(site.defaultLocale)}" aria-labelledby="demo-title"><p class="eyebrow">${e(demo.label)}</p><h2 id="demo-title">${e(demo.title)}</h2><p>${e(demo.description)}</p><p class="small">${e(demo.disclaimer)}</p><div data-demo-controls hidden><label for="demo-select">Explore a case</label><select id="demo-select" data-demo-select>${demo.cases.map(c => `<option value="${e(c.id)}">${e(c.title)}</option>`).join('')}</select></div><div data-demonstration>${demo.cases.map(c => `<article data-demo-case="${e(c.id)}"><h3>${e(c.title)}</h3><p>${e(c.description)}</p><dl>${c.fields.map(f => `<div><dt>${e(f.label)}</dt><dd>${e(f.value)}</dd></div>`).join('')}</dl><p class="demo-conclusion">${e(c.conclusion)}</p></article>`).join('')}</div></section>` : '';
  const ecosystem = `<section class="ecosystem" id="together"><p class="eyebrow">A cooperative workshop</p><h2>Four responsibilities. One clearer story.</h2><p>Use one tool where it helps, or connect the whole workshop. People keep the purpose and judgment; the tools make the work easier to explain.</p><div class="ecosystem-grid">${FLEET.map(p => `<a href="${p.origin}" class="ecosystem-card${p.id === site.slug ? ' current' : ''}"><span class="eyebrow">${p.id === site.slug ? 'You are here' : 'Works alongside'}</span><strong>${p.name}</strong><span>${p.role}</span></a>`).join('')}</div></section>`;
  const workflow = site.workflow?.length ? `<section class="workflow" id="workflow"><p class="eyebrow">From intention to understanding</p><h2>A workflow you can explain to another person</h2><ol>${site.workflow.map(step => `<li><h3>${e(step.title)}</h3><p>${e(step.text)}</p>${step.href ? `<a href="${e(step.href)}">${e(step.linkLabel || 'Explore this step')} →</a>` : ''}</li>`).join('')}</ol></section>` : '';
  const quickstart = site.quickstart ? `<section class="quickstart" id="quickstart"><div><p class="eyebrow">A small first step</p><h2>${e(site.quickstart.title)}</h2><p>${e(site.quickstart.summary)}</p><p class="small">${e(site.quickstart.note)}</p></div><div>${site.quickstart.commands.map(command => `<h3>${e(command.label)}</h3><pre><code>${e(command.code)}</code></pre>`).join('')}<a href="${e(site.quickstart.href)}">Full installation and operating guide →</a></div></section>` : '';
  const cards = publications(site).map(p => `<article class="publication-card" data-date="${e(p.published)}" data-title="${e(p.title)}"><p class="eyebrow">${e(p.status)} · ${e(p.published)}</p><h2><a href="${e(pagePath(site, p, locale))}">${e(edition(site, p, locale).title)}</a></h2><p class="card-description">${e(edition(site, p, locale).description)}</p></article>`).join('');
  let body;
  if (missing) body = `<section class="hero compact"><p class="eyebrow">404</p><h1>This page is missing.</h1><a href="${e(mounted(site))}">Return to ${e(site.name)}</a></section>`;
  else if (listing) body = `${article}<section><p class="eyebrow">Practical companions</p><h1>Guides & documentation</h1><div class="catalog-controls"><label>Layout <select data-catalog-layout><option value="grid">Grid</option><option value="list">List</option></select></label><label>Sort <select data-catalog-sort><option value="date">Publication date</option><option value="name">Name</option></select></label></div><div class="publications" data-catalog>${cards}</div></section>`;
  else if (contact) body = `<section class="hero compact"><p class="eyebrow">RAGBAZ / ${e(site.name)}</p><h1>Let’s make something worthwhile.</h1><p>Questions, thoughtful doubts, practical needs and offers of help are all welcome.</p>${sent?'<p role="status">Thank you for reaching out. If your submission was accepted, it is recorded for the studio.</p>':''}</section>`;
  else body = `<section class="hero${isHome ? '' : ' compact'}"><div class="hero-copy"><p class="eyebrow">RAGBAZ / ${e(active?.motif || site.slug)} / ${e(site.name)}</p><h1>${e(content.title)}</h1><p class="deck" lang="${e(site.defaultLocale)}">${e(isHome ? site.tagline : content.description)}</p>${isHome ? `<p class="hero-description">${e(content.description)}</p><div class="actions">${links}<a class="button quiet" href="#interest">Talk to us</a></div>` : ''}<p class="status">${e(isHome ? site.status : `${page.status} · Updated ${page.updated}`)}</p></div>${isHome ? `<div class="hero-emblem"><img src="${e(mounted(site, site.logo || '/assets/mark.svg'))}" alt="${e(site.name)} project mark"><p>${e(site.motifCaption || 'Work that can be held up to the light.')}</p></div>` : ''}</section>${isHome ? highlights + article : ''}${content.fallback ? '<p class="translation-note">This document is not translated into the requested language. Showing the original edition.</p>' : ''}<nav class="contents" aria-label="On this page">${content.sections.map(s => `<a href="#${e(s.id)}">${e(s.title)}</a>`).join('')}</nav>${sections}${isHome ? THREAD + ecosystem + workflow + quickstart : ''}`;
  let education = '';
  if (site.modules.education && !missing && !listing && !contact) {
    const lessons = site.lessons.map(id => site.pages.find(p => p.id === id)), position = lessons.findIndex(p => p.id === page.id);
    education = `<aside class="reader-controls" data-education data-project="${e(site.slug)}" data-lessons="${e(site.lessons.join(','))}" data-lesson="${e(page.id)}"><nav aria-label="Lesson sequence">${position > 0 ? `<a href="${e(pagePath(site, lessons[position - 1], locale))}">Previous lesson</a>` : ''}${position >= 0 && position < lessons.length - 1 ? `<a href="${e(pagePath(site, lessons[position + 1], locale))}">Next lesson</a>` : ''}</nav>${position >= 0 ? '<button type="button">Mark as read</button>' : ''}<p role="status" aria-live="polite">Progress is recorded only on this device.</p></aside>`;
  }
  if (isHome) body += demonstration;
  const scripts = [...(site.schema === 'ragbaz.project-site/v1' ? ['chrome.js'] : []), ...(site.modules.reader ? ['reader.js'] : []), ...(listing ? ['catalog.js'] : []), ...(site.modules.contact && !missing ? ['contact.js'] : []), ...(education ? ['education.js'] : []), ...(site.modules.demonstration && isHome ? ['demonstration.js'] : [])];
  const footer = `<footer class="studio-footer"><div><a class="studio-brand" href="https://ragbaz.cc">${MARK}<span>RAGBAZ<small>Technology in the service of life.</small></span></a><p>A software studio working for the good of all beings: with loving kindness, honest evidence and mutual cooperation.</p><p class="small">These tools make work more accountable. They do not, by themselves, settle AI’s existential risks or guarantee that people and systems cannot cause harm.</p></div><nav aria-label="RAGBAZ projects">${FLEET.map(p => `<a href="${p.origin}">${p.name}</a>`).join('')}${STUDIO.map(l => `<a href="${l.href}">${l.name}</a>`).join('')}<a href="${e(mounted(site, '/privacy/'))}">Privacy & attribution</a></nav><p class="footer-meta">${e(site.name)} · Content updated ${e(site.updated)} · <a href="mailto:ragbaz@proton.me">ragbaz@proton.me</a></p></footer>`;
  return `<!doctype html><html lang="${e(content.locale)}" dir="${content.dir}" data-project="${e(active?.motif || 'loom')}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(content.description)}">${missing || page.status === 'archived' ? '<meta name="robots" content="noindex">' : `<link rel="canonical" href="${e(canonical)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(content.description)}"><meta property="og:type" content="website">${site.socialImage ? `<meta property="og:image" content="${e(site.origin + mounted(site, site.socialImage))}"><meta name="twitter:card" content="summary_large_image">` : ''}${!listing && !contact ? availableLocales(site, page).map(l => `<link rel="alternate" hreflang="${e(l.code)}" href="${e(site.origin + pagePath(site, page, l.code))}">`).join('') : ''}`}<link rel="icon" href="${e(mounted(site, site.logo || '/assets/mark.svg'))}" type="image/svg+xml">${['tokens.css','site-tokens.css','site.css', ...(site.modules.reader ? ['reader.css'] : [])].map(a => `<link rel="stylesheet" href="${e(mounted(site, '/assets/' + a))}">`).join('')}${scripts.map(s => `<script src="${e(mounted(site, '/assets/' + s))}" defer></script>`).join('')}</head><body><a class="skip" href="#main">Skip to content</a>${header}<div class="reading-toolbar">${!listing && !contact && !missing && availableLocales(site, page).length > 1 ? `<nav class="language-nav" aria-label="Languages">${locales}</nav>` : ''}${reader}</div><main id="main">${body}${education}${site.modules.contact && !missing ? contactForm(site, page, e) : ''}</main>${footer}</body></html>`;
}
